// Auto-generated registry index
// Maps component names to their file paths for CLI installation

export const registry = {
  button: {
    name: "button",
    type: "registry:ui",
    files: ["components/ui/primitives/button.tsx", "lib/utils.ts"],
    dependencies: ["@radix-ui/react-slot", "class-variance-authority"],
    registryDependencies: [],
  },
  card: {
    name: "card",
    type: "registry:ui",
    files: ["components/ui/primitives/card.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  cards: {
    name: "cards",
    type: "registry:ui",
    files: ["components/ui/compositions/cards.tsx", "lib/utils.ts"],
    dependencies: ["gsap", "@gsap/react"],
    registryDependencies: [],
  },
  input: {
    name: "input",
    type: "registry:ui",
    files: ["components/ui/primitives/input.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  "morphing-text": {
    name: "morphing-text",
    type: "registry:ui",
    files: ["components/ui/primitives/morphing-text.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  "mouse-follower": {
    name: "mouse-follower",
    type: "registry:ui",
    files: ["components/ui/compositions/mouse-follower.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  parallax: {
    name: "parallax",
    type: "registry:ui",
    files: ["components/ui/compositions/parallax.tsx", "lib/utils.ts"],
    dependencies: ["gsap", "@gsap/react"],
    registryDependencies: [],
  },
  "spinning-text": {
    name: "spinning-text",
    type: "registry:ui",
    files: ["components/ui/primitives/spinning-text.tsx", "lib/utils.ts"],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  accordion: {
    name: "accordion",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/accordion.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "action-icons": {
    name: "action-icons",
    type: "registry:ui",
    files: ["components/icons/animated/action-icons.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  "alert-dialog": {
    name: "alert-dialog",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/alert-dialog.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "alert-icon": {
    name: "alert-icon",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/alert.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "aspect-ratio": {
    name: "aspect-ratio",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/aspect-ratio.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  avatar: {
    name: "avatar",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/avatar.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  badge: {
    name: "badge",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/badge.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  book: {
    name: "book",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/book.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  breadcrumb: {
    name: "breadcrumb",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/breadcrumb.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "button-group": {
    name: "button-group",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/button-group.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "button-icon": {
    name: "button-icon",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/button.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  calendar: {
    name: "calendar",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/calendar.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "card-icon": {
    name: "card-icon",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/card.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  carousel: {
    name: "carousel",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/carousel.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  chart: {
    name: "chart",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/chart.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  checkbox: {
    name: "checkbox",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/checkbox.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "collapsible-icon": {
    name: "collapsible-icon",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/collapsible.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  combobox: {
    name: "combobox",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/combobox.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "command-icon": {
    name: "command-icon",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/command.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "context-menu": {
    name: "context-menu",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/context-menu.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "data-table": {
    name: "data-table",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/data-table.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "dialog-icon": {
    name: "dialog-icon",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/dialog.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  flask: {
    name: "flask",
    type: "registry:ui",
    files: ["components/icons/animated/flask.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  github: {
    name: "github",
    type: "registry:ui",
    files: ["components/icons/animated/github.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  heart: {
    name: "heart",
    type: "registry:ui",
    files: ["components/icons/animated/heart.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  "input-icon": {
    name: "input-icon",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/input.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  layers: {
    name: "layers",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/layers.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "light-dark-mode": {
    name: "light-dark-mode",
    type: "registry:ui",
    files: ["components/icons/animated/light-dark-mode.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  menu: {
    name: "menu",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/menu.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  moon: {
    name: "moon",
    type: "registry:ui",
    files: ["components/icons/animated/moon.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  notification: {
    name: "notification",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/notification.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  pagination: {
    name: "pagination",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/pagination.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  progress: {
    name: "progress",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/progress.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  radio: {
    name: "radio",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/radio.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  search: {
    name: "search",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/search.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  select: {
    name: "select",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/select.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  settings: {
    name: "settings",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/settings.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  shield: {
    name: "shield",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/shield.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  slider: {
    name: "slider",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/slider.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  sun: {
    name: "sun",
    type: "registry:ui",
    files: ["components/icons/animated/sun.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  switch: {
    name: "switch",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/switch.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "tabs-icon": {
    name: "tabs-icon",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/tabs.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  "tooltip-icon": {
    name: "tooltip-icon",
    type: "registry:icon",
    files: [
      "components/icons/animated/icons/tooltip.tsx",
      "components/icons/animated/motion-icon.tsx",
      "components/icons/animated/icon-variants.ts",
      "components/icons/animated/types.ts",
    ],
    dependencies: ["motion/react"],
    registryDependencies: [],
  },
  twitter: {
    name: "twitter",
    type: "registry:ui",
    files: ["components/icons/animated/twitter.tsx", "lib/utils.ts"],
    dependencies: [],
    registryDependencies: [],
  },
  "12-dots-scale-rotate": {
    name: "12-dots-scale-rotate",
    type: "registry:ui",
    files: ["registry/generated/loaders/12-dots-scale-rotate.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "180-ring-with-bg": {
    name: "180-ring-with-bg",
    type: "registry:ui",
    files: ["registry/generated/loaders/180-ring-with-bg.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "180-ring": {
    name: "180-ring",
    type: "registry:ui",
    files: ["registry/generated/loaders/180-ring.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "270-ring-with-bg": {
    name: "270-ring-with-bg",
    type: "registry:ui",
    files: ["registry/generated/loaders/270-ring-with-bg.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "270-ring": {
    name: "270-ring",
    type: "registry:ui",
    files: ["registry/generated/loaders/270-ring.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "3-dots-bounce": {
    name: "3-dots-bounce",
    type: "registry:ui",
    files: ["registry/generated/loaders/3-dots-bounce.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "3-dots-fade": {
    name: "3-dots-fade",
    type: "registry:ui",
    files: ["registry/generated/loaders/3-dots-fade.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "3-dots-move": {
    name: "3-dots-move",
    type: "registry:ui",
    files: ["registry/generated/loaders/3-dots-move.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "3-dots-rotate": {
    name: "3-dots-rotate",
    type: "registry:ui",
    files: ["registry/generated/loaders/3-dots-rotate.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "3-dots-scale-middle": {
    name: "3-dots-scale-middle",
    type: "registry:ui",
    files: ["registry/generated/loaders/3-dots-scale-middle.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "3-dots-scale": {
    name: "3-dots-scale",
    type: "registry:ui",
    files: ["registry/generated/loaders/3-dots-scale.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "6-dots-rotate": {
    name: "6-dots-rotate",
    type: "registry:ui",
    files: ["registry/generated/loaders/6-dots-rotate.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "6-dots-scale-middle": {
    name: "6-dots-scale-middle",
    type: "registry:ui",
    files: ["registry/generated/loaders/6-dots-scale-middle.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "6-dots-scale": {
    name: "6-dots-scale",
    type: "registry:ui",
    files: ["registry/generated/loaders/6-dots-scale.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "8-dots-rotate": {
    name: "8-dots-rotate",
    type: "registry:ui",
    files: ["registry/generated/loaders/8-dots-rotate.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "90-ring-with-bg": {
    name: "90-ring-with-bg",
    type: "registry:ui",
    files: ["registry/generated/loaders/90-ring-with-bg.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "90-ring": {
    name: "90-ring",
    type: "registry:ui",
    files: ["registry/generated/loaders/90-ring.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  audio: {
    name: "audio",
    type: "registry:ui",
    files: ["registry/generated/loaders/audio.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "ball-triangle": {
    name: "ball-triangle",
    type: "registry:ui",
    files: ["registry/generated/loaders/ball-triangle.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "bars-fade": {
    name: "bars-fade",
    type: "registry:ui",
    files: ["registry/generated/loaders/bars-fade.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "bars-rotate-fade": {
    name: "bars-rotate-fade",
    type: "registry:ui",
    files: ["registry/generated/loaders/bars-rotate-fade.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "bars-scale-fade": {
    name: "bars-scale-fade",
    type: "registry:ui",
    files: ["registry/generated/loaders/bars-scale-fade.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "bars-scale-middle": {
    name: "bars-scale-middle",
    type: "registry:ui",
    files: ["registry/generated/loaders/bars-scale-middle.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "bars-scale": {
    name: "bars-scale",
    type: "registry:ui",
    files: ["registry/generated/loaders/bars-scale.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  bars: {
    name: "bars",
    type: "registry:ui",
    files: ["registry/generated/loaders/bars.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "blocks-scale": {
    name: "blocks-scale",
    type: "registry:ui",
    files: ["registry/generated/loaders/blocks-scale.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "blocks-shuffle-2": {
    name: "blocks-shuffle-2",
    type: "registry:ui",
    files: ["registry/generated/loaders/blocks-shuffle-2.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "blocks-shuffle-3": {
    name: "blocks-shuffle-3",
    type: "registry:ui",
    files: ["registry/generated/loaders/blocks-shuffle-3.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "blocks-wave": {
    name: "blocks-wave",
    type: "registry:ui",
    files: ["registry/generated/loaders/blocks-wave.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "bouncing-ball": {
    name: "bouncing-ball",
    type: "registry:ui",
    files: ["registry/generated/loaders/bouncing-ball.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  circles: {
    name: "circles",
    type: "registry:ui",
    files: ["registry/generated/loaders/circles.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  clock: {
    name: "clock",
    type: "registry:ui",
    files: ["registry/generated/loaders/clock.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "dot-revolve": {
    name: "dot-revolve",
    type: "registry:ui",
    files: ["registry/generated/loaders/dot-revolve.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "eclipse-half": {
    name: "eclipse-half",
    type: "registry:ui",
    files: ["registry/generated/loaders/eclipse-half.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  eclipse: {
    name: "eclipse",
    type: "registry:ui",
    files: ["registry/generated/loaders/eclipse.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "gooey-balls-1": {
    name: "gooey-balls-1",
    type: "registry:ui",
    files: ["registry/generated/loaders/gooey-balls-1.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "gooey-balls-2": {
    name: "gooey-balls-2",
    type: "registry:ui",
    files: ["registry/generated/loaders/gooey-balls-2.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  grid: {
    name: "grid",
    type: "registry:ui",
    files: ["registry/generated/loaders/grid.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  hearts: {
    name: "hearts",
    type: "registry:ui",
    files: ["registry/generated/loaders/hearts.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  oval: {
    name: "oval",
    type: "registry:ui",
    files: ["registry/generated/loaders/oval.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  puff: {
    name: "puff",
    type: "registry:ui",
    files: ["registry/generated/loaders/puff.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "pulse-2": {
    name: "pulse-2",
    type: "registry:ui",
    files: ["registry/generated/loaders/pulse-2.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "pulse-3": {
    name: "pulse-3",
    type: "registry:ui",
    files: ["registry/generated/loaders/pulse-3.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "pulse-multiple": {
    name: "pulse-multiple",
    type: "registry:ui",
    files: ["registry/generated/loaders/pulse-multiple.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "pulse-ring": {
    name: "pulse-ring",
    type: "registry:ui",
    files: ["registry/generated/loaders/pulse-ring.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "pulse-rings-2": {
    name: "pulse-rings-2",
    type: "registry:ui",
    files: ["registry/generated/loaders/pulse-rings-2.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "pulse-rings-3": {
    name: "pulse-rings-3",
    type: "registry:ui",
    files: ["registry/generated/loaders/pulse-rings-3.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "pulse-rings-multiple": {
    name: "pulse-rings-multiple",
    type: "registry:ui",
    files: ["registry/generated/loaders/pulse-rings-multiple.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  pulse: {
    name: "pulse",
    type: "registry:ui",
    files: ["registry/generated/loaders/pulse.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "ring-resize": {
    name: "ring-resize",
    type: "registry:ui",
    files: ["registry/generated/loaders/ring-resize.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  rings: {
    name: "rings",
    type: "registry:ui",
    files: ["registry/generated/loaders/rings.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "spinning-circles": {
    name: "spinning-circles",
    type: "registry:ui",
    files: ["registry/generated/loaders/spinning-circles.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  tadpole: {
    name: "tadpole",
    type: "registry:ui",
    files: ["registry/generated/loaders/tadpole.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "tail-spin": {
    name: "tail-spin",
    type: "registry:ui",
    files: ["registry/generated/loaders/tail-spin.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "three-dots": {
    name: "three-dots",
    type: "registry:ui",
    files: ["registry/generated/loaders/three-dots.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "wifi-fade": {
    name: "wifi-fade",
    type: "registry:ui",
    files: ["registry/generated/loaders/wifi-fade.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  wifi: {
    name: "wifi",
    type: "registry:ui",
    files: ["registry/generated/loaders/wifi.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
  "wind-toy": {
    name: "wind-toy",
    type: "registry:ui",
    files: ["registry/generated/loaders/wind-toy.tsx"],
    dependencies: [],
    registryDependencies: ["utils"],
  },
} as const

export type ComponentName = keyof typeof registry
